import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';

const Home: NextPage = () => {
  const [address, setAddress] = useState('');

  useEffect(() => {
    if (address) {
      // Perform actions when address changes
      console.log('Address updated:', address);
      // You can add more logic here, such as fetching balances
    }
  }, [address]);

  const handleSeeBalances = () => {
    // TODO: Implement balance checking logic
    console.log('Checking balances for:', address);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>
          Welcome to <a href="https://github.com/duneanalytics/hooks" target="_blank">Dune Hooks</a> + <a href="">wagmi</a> +{' '}
          <a href="">Rainbokit</a>
        </h1>
        
        <ConnectButton showBalance={false}/>
        </main>

      <footer className={styles.footer}>
        <a href="https://dune.com" target="_blank">
          Made with ❤️ by your frens at Dune
        </a>
      </footer>
    </div>
  );
};

export default Home;
